### ISSUE TITLE
Bevindingen nieuwe specificaties (door Marco van 't Wout)

### ISSUE THREAD

**Issue by JosVanderArend** [edustandaard/doorstroomtoets#13]
**_Marco van 't Wout op 2 en 7 augustus 2023:_** 

Bij de verwerking heb ik geen echte fouten gevonden, wel een verzameling kleine puntjes waar je misschien nog iets mee wilt doen:
1.	Het veld Doorstroomtoets.id maakt nu gebruik van de nieuwe Toetssoort_enum. Maar deze is niet toegepast op LeerlingResultatenScores.toetsdefinitie, die dezelfde waardes zou moeten hebben?
2.	Het veld Deelnemersgroep.vestigingscode heeft als example "0" in plaats van "00".
3.	Het veld Doorstroomtoets.versie is nog steeds een verplicht veld, terwijl deze volgens de specificaties optioneel zou worden. Vervolgens hebben we met Doorstroomtoets.versie en Doorstroomtoets.omschrijving eigenlijk twee vrije velden, wat ons betreft is één van de twee voldoende.
4.	Het veld Score.toetseenheid heeft als example "AMN", dit zou iets anders moeten zijn zoals "REKENEN".
5.	Uit de paden is "eindtoets" vervallen (bijv /eindtoets/registreren is nu /registreren). Het lijkt me goed de ketenpartners hierop te wijzen. Aangezien endpoints vooraf gedeeld worden kan iedere partij dan expliciet aangeven of "eindtoets" daaraan moet worden toegevoegd of niet.
6.	De PDF-specificatie op pagina 25 van de 36 benoemt nog waardes "01 t/m 04", waar die nu vervangen zijn door "L1F t/m 2F".

Nog 1 toevoeging:
1.	Het veld Onderwijsdeelnemer.voorletters heeft in de PDF-spec een maximale lengte van "6", maar deze is niet opgenomen als maxLength in de YAML.

Allemaal geen breekpunten die een nieuwe versie vereisen, hoeft wat mij betreft pas meegenomen worden in het concept voor volgend jaar.

**Comment by JosVanderArend** [comment]
Dank voor je terugkoppeling. 
 
Het zijn allemaal terechte opmerkingen. 
Ik dacht nog even dat de opmerking over het vervallen van eindtoets uit de paden onterecht was want er is op dit vlak niet veel veranderd in de OAS3-definities.
Maar je doelde waarschijnlijk op de wijzigingen van de endpoints in het specificatiedocument (het PDF-bestand). En dan met name het ontbreken van de vermelding in de documenthistorie. En over het ontbreken van de gele markering in de versie met kleurmarkeringen.
 
Ik denk ook dat deze aanpassingen niet direct een nieuwe versie vereisen. Ik heb ze in elk geval alvast genoteerd zodat ze worden meegenomen in een volgende versie!

**Comment by JosVanderArend** [comment]
**_Marco van 't Wout op 15 augustus 2023:_** 

Wat betreft de wijziging in paden/endpoints, misschien dat dit vorig jaar al half was doorgevoerd. We hadden eerder dit gerelateerd issue: https://github.com/JosVanderArend/eindtoets/issues/2

Uiteindelijk gaat het erom dat duidelijk is wat het volledige pad is waar een call naartoe gaat. Dat pad bestaat uit het endpoint van de leverancier (bijv: https://api.iepdoorstroomtoets.nl/las/v2023-2024) plus de actie uit de YAML-specificatie (bijv: "/registreren"). Vroeger had die actie "eindtoets/registreren" als pad, daarna is "eindtoets/" vervallen. Dus misschien dat het nu niet voor iedereen duidelijk is of dat er nog in hoort of niet.

Voor het endpoint van ICE heb ik in deze sheet vermeld dat er een aanpassing is en dat wij dit laten vervallen: https://365kennisnet.sharepoint.com/:x:/r/sites/LogistiekProcesEindtoetsPO/_layouts/15/Doc.aspx?sourcedoc=%7B5CBABA00-D992-4EF7-BC03-F464FA377A87%7D&file=2023-2024%20Beschikbare%20testmomenten%20en%20endpoints%20ketenpartners.xlsx&action=default&mobileredirect=true. Andere leveranciers zullen er misschien voor kiezen "eindtoets" te behouden maar dan moet dat worden toegevoegd aan het gedocumenteerde endpoint in de sheet.

**Comment by marcovtwout** [comment]
Alle bevindingen opgelost, ticket kan dicht.

**Comment by JosVanderArend** [comment]
Opgelost in versie 1.0.1
